apiVersion: v1
kind: Service
metadata:
  name: go-web-app-service
  namespace: my-go-web-app
spec:
  type: NodePort
  selector:
    app: go-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Optional: specify a port (30000-32767)
